buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath("io.github.tiktok.knit:knit-plugin:0.1.4")
    }
}

plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "2.1.0"
    id("com.gradleup.shadow") version "8.3.6"
    id("application")
}

apply(plugin = "io.github.tiktok.knit.plugin")

group = "com.example.knit"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.github.tiktok.knit:knit:0.1.4")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    
    // Optional: For better logging
    implementation("ch.qos.logback:logback-classic:1.4.14")
    
    testImplementation("org.jetbrains.kotlin:kotlin-test")
}

application {
    mainClass.set("com.example.knit.demo.main.MainApplicationKt")
}

tasks {
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "17"
            freeCompilerArgs = listOf("-Xjsr305=strict")
        }
    }
    
    withType<JavaCompile> {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    shadowJar {
        archiveClassifier.set("")
        mergeServiceFiles()
    }

    // Use shadowJarWithKnit task generated by Knit plugin
    register("runWithKnit") {
        dependsOn("shadowJarWithKnit")
        doLast {
            println("✅ Knit DI Demo built successfully with shadowJarWithKnit!")
            println("📁 Jar location: build/libs/${project.name}-${project.version}.jar")
            println("🚀 Run with: java -jar build/libs/${project.name}-${project.version}.jar")
        }
    }
}

kotlin {
    jvmToolchain(17)
}